config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :employees

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "reimbursements#index"
  resources :reimbursements, only: [ :index, :new, :create ]
  resources :leaves, only: [ :index, :new, :create, :edit, :update ] do
    member do
      put :approve
      put :reject
    end
    collection do
      post :cancel
    end
  end

  get "*path" => redirect("/"), constraints: lambda { |req| !req.path.starts_with?("/rails/active_storage") }
end

app/models/leave.rb
class Leave < ApplicationRecord
  belongs_to :employee
  belongs_to :approver, class_name: "AdminUser"
  belongs_to :processed_by, class_name: "AdminUser", optional: true

  validates :employee_id, presence: true
  validates :approver_id, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :day_count, presence: true
  validates :leave_type, presence: true

  validate :end_date_must_be_after_start_date, :day_count_must_be_countable, :no_overlapping_dates

  scope :sick_leaves, -> { where(leave_type: "sick") }
  scope :vacation_leaves, -> { where(leave_type: "vacation") }
  scope :pending_leaves, -> { where(status: "pending").order("start_date asc") }
  scope :approved_leaves, -> { where(status: "approved").order("start_date asc") }
  scope :counted_leaves, -> { where(status: [ "pending", "approved" ]) }
  scope :uncounted_leaves, -> { where(status: [ "rejected", "cancelled" ]) }

  private

  def end_date_must_be_after_start_date
    if start_date.present? && end_date.present? && start_date > end_date
      errors.add(:end_date, "must be after the start date.")
    end
  end

  def day_count_must_be_countable
    if day_count < 1
      errors.add(:day_count, "must be greater than 0.")
    end
  end

  def no_overlapping_dates
    overlaps = Leave.counted_leaves.where.not(id: id).where(employee_id: employee_id).where("start_date <= ? and end_date >= ?", end_date, start_date)
    if !overlaps.empty?
      errors.add(:base, "Leave request shouldn't overlap with other leaves.")
    end
  end
end

app/controllers/leaves_controller.rb
class LeavesController < ApplicationController
  before_action :authenticate_employee!, only: [ :index, :new, :create, :edit, :update ]
  before_action :approvers, only: [ :new, :create, :edit, :update ]
  before_action :find_id, only: [ :edit, :update, :cancel ]
  before_action :leave_counts, only: [ :index, :new, :create, :edit, :update ]

  # include LeavesHelper
  def index
    @leaves = @all_leaves

    @months = [ *1..12 ].map { |m| [ Date::MONTHNAMES[m], m ] }
    @years = @all_leaves.pluck(:start_date, :end_date).flatten.map { |d| d.year }.uniq

    # filtered leaves
    @leaves = @leaves.where(leave_type: params[:leave_type].downcase) if params[:leave_type].present?
    @leaves = @leaves.where(status: params[:status].downcase) if params[:status].present?
    @leaves = @leaves.where("extract(month from start_date) = ? or extract(month from end_date) = ?", params[:month], params[:month]) if params[:month].present?
    @leaves = @leaves.where("extract(year from start_date) = ? or extract(year from end_date) = ?", params[:year], params[:year]) if params[:year].present?

    @past_leaves = @leaves.where(start_date: ..(Date.today-1.day)).order("start_date desc")
    @upcoming_leaves = @leaves.where(start_date: (Date.today)..).order("start_date asc")
  end

  def new
    @leave = Leave.new
  end

  def create
    @leave = current_employee.leaves.build(leave_params)
    if @leave.save
      flash[:success] = @leave.leave_type.capitalize + " leave request filed successfully."
      redirect_to leaves_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    if @leave.leave_type == "sick"
      @remaining_sl += @leave.day_count
    elsif @leave.leave_type == "vacation"
      @remaining_vl += @leave.day_count
    end
  end

  def update
    if @leave.update(leave_params)
      flash[:success] = @leave.leave_type.capitalize + " leave request updated successfully."
      redirect_to leaves_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def cancel
    if @leave.update(status: "cancelled")
      flash[:success] = "Leave request cancelled!"
      redirect_to leaves_path
    else
      render :index, status: :unprocessable_entity
    end
  end

  private

  def leave_params
    params.require(:leave).permit(:approver_id, :start_date, :end_date, :day_count, :leave_type, :reason)
  end

  def find_id
    @leave = Leave.find(params[:id])
  end

  def approvers
    @approvers = AdminUser.order(:email)
  end

  def leave_counts
    @all_leaves = current_employee.leaves

    @pending_sl = @all_leaves.sick_leaves.pending_leaves.sum(:day_count)
    @pending_vl = @all_leaves.vacation_leaves.pending_leaves.sum(:day_count)
    @approved_sl = @all_leaves.sick_leaves.approved_leaves.sum(:day_count)
    @approved_vl = @all_leaves.vacation_leaves.approved_leaves.sum(:day_count)
    @remaining_sl = 15 - @approved_sl - @pending_sl
    @remaining_vl = 15 - @approved_vl - @pending_vl
  end
end

app/helpers/leaves_helper.rb
module LeavesHelper
  def get_status_badge(status)
    if status == "approved"
      "text-bg-success"
    elsif status == "rejected"
      "text-bg-danger"
    elsif status == "pending"
      "text-bg-warning"
    else
      "text-bg-secondary"
    end
  end

  def get_type_border(type)
    if type == "sick"
      "border-warning"
    elsif type == "vacation"
      "border-info"
    end
  end
end

app/views/leaves/_form.html.erb
<%= render 'shared/flashes' %>
<% if @leave.errors.any? %>
  <% @leave.errors.full_messages.each do |message| %>
    <div class="alert alert-danger"><%= message %></div>
  <% end %>
<% end %>

<%= form_with(model: @leave, data: { controller: "leave-request", action: "submit->leave-request#validateForm" }) do |f| %>
  <div class="row my-2">
    <%= f.label :approver_id, class: "form-label" %>
    <span>
      <%= f.collection_select :approver_id, @approvers || [], :id, :email, { prompt: "Select an approver" }, class: "form-select", required: true %>
    </span>
  </div>
  <div class="row my-2">
    <div class="col-5">
      <%= f.label :start_date, class: "form-label" %>
      <%= f.date_field :start_date, class: "form-control", required: true,
        data: {
          "leave-request-target": "startDate",
          action: "change->leave-request#handleStartDateChange"
        } %>
      </div>
      <div class="col-5">
      <%= f.label :end_date, class: "form-label" %>
      <%= f.date_field :end_date, class: "form-control", required: true,
        data: {
          "leave-request-target": "endDate",
          action: "change->leave-request#handleEndDateChange"
        } %>
      </div>
      <div class="col-2">
      <%= f.label :day_count, class: "form-label" %>
      <%= f.number_field :day_count, class: "form-control", min: 1, required: true, 
        data: {
          "leave-request-target": "dayCount",
          action: "input->leave-request#handleDayCountChange"
        } %>
    </div>
  </div>
  <div class="row my-2">
    <div class="col-5">
      <%= f.label :leave_type, class: "form-label" %>
      <div class="border rounded">
        <div class="px-3 py-1 border-bottom">
          <%= f.radio_button :leave_type, "sick", class: "form-check-input mx-1", required: true,
            data: {
              action: "input->leave-request#handleTypeSelect"
            } %>
          <%= f.label :leave_type_sick, "Sick", class: "form-check-label" %>
          (<span data-leave-request-target="remainingSL"><%= @remaining_sl < 0 ? 0 : @remaining_sl %></span> left)
        </div>
        <div class="px-3 py-1">
          <%= f.radio_button :leave_type, "vacation", class: "form-check-input mx-1",
            data: {
              action: "input->leave-request#handleTypeSelect"
            } %>
          <%= f.label :leave_type_vacation, "Vacation", class: "form-check-label" %>
          (<span data-leave-request-target="remainingVL"><%= @remaining_vl < 0 ? 0 : @remaining_vl %></span> left)
        </div>
      </div>
    </div>
    <div class="col-7">
      <%= f.label :reason, class: "form-label" %>
      <%= f.text_area :reason, class: "form-control" %>
    </div>
  </div>

  <div data-controller="modal">
    <%= render "modal",
          title: "File leave",
          content: "Your leave's day count is greater than your remaining leaves. Are you sure you want to file it anyway?",
          form: f
    %>
  </div>

  <div class="d-flex my-3">
    <%= f.submit 'File Leave', class: "btn btn-success col-12" %>
  </div>
<% end %>

app/views/leaves/_header.html.erb
<div class="py-2 hero-section fixed-top z-2" style="margin-top: 56px;">
  <div class="container col-12 col-lg-6 py-4">
    <div class="row align-items-center me-2">
      <h2 class="col-9 fw-bold"><%= current_employee.nickname %>'s time off</h2>
      <a class="col-3 btn btn-success" href="<%= new_leave_path() %>">
        File Leave
      </a>
    </div>

    <div class="mt-4">
      <%= form_with(url: leaves_path, method: :get) do |f| %>
        <div class="card">
          <div class="card-body">
            <h5 class="card-title mx-2">Filters</h5>
            <div class="d-flex flex-row align-items-center">
              <div class="mx-2">
                <%= f.select :leave_type, options_for_select(["Sick", "Vacation"], selected: params[:leave_type]), { prompt: "Select type" }, class: "form-select" %>
              </div>
              <div class="mx-2">
                <%= f.select :status, options_for_select(["Pending", "Approved", "Rejected", "Cancelled"], selected: params[:status]), { prompt: "Select status" }, class: "form-select" %>
              </div>
              <div class="mx-2">
                <%= f.select :month, options_for_select(@months, selected: params[:month]), { prompt: "Select month" }, class: "form-select" %>
              </div>
              <div class="mx-2">
                <%= f.select :year, options_for_select(@years, selected: params[:year]), { prompt: "Select year" }, class: "form-select" %>
              </div>
              <div class="mx-2 w-25">
                <%= f.submit "Filter", class: "btn btn-primary w-100" %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/leaves/_modal.html.erb
<div
  class="modal fade"
  tabindex="-1"
  role="dialog"
  aria-hidden="false"
  data-modal-target="modal"
  data-action="modal-open@window->modal#open"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title fs-5" id="exampleModalLabel">
          <%= title %>
        </h4>
        <button type="button" class="btn-close" data-action="modal#close" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= content %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-action="modal#close">No</button>
        <% if !form.nil? %>
          <%= form.submit "Yes", class: "btn btn-primary", id: "modalConfirm" %>
        <% else %>
          <button type="button" class="btn btn-primary">Yes</button>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/leaves/edit.html.erb
<div class="container col-12 col-md-6 py-4">
  <h2>Edit Leave Request</h2>
  <%= render "form", leave: @leave %>
</div>

app/views/leaves/index.html.erb
<%= render "header" %>

<div class="container col-lg-6 py-2 z-1" style="margin-top: 300px;" data-controller="tooltip">
  <%= render "shared/flashes" %>

  <div class="my-2 d-flex flex-row">
    <div class="card w-50 me-2 alert alert-warning">
      <% if @remaining_sl < 0 %>
        <span class="position-absolute end-0 me-3 mt-1" data-bs-toggle="tooltip" data-bs-title="You've filed more than 15 SLs (<%= -@remaining_sl %> above limit)">
          <i style="width: 24px; height: 24px;" class="fa-solid fa-circle-exclamation"></i>
        </span>
      <% end %>
      <h3>SL: <span class="fw-bold"><%= @remaining_sl < 0 ? 0 : @remaining_sl %>/15</span> remaining</h3>
      <div>
        <span class="fw-bold"><%= @approved_sl %></span> approved,
        <span class="fw-bold"><%= @pending_sl %></span> pending
      </div>
    </div>
    <div class="w-50 ms-2 alert alert-info">
      <% if @remaining_vl < 0 %>
        <span class="position-absolute end-0 me-3 mt-1" data-bs-toggle="tooltip" data-bs-title="You've filed more than 15 VLs (<%= -@remaining_vl %> above limit)">
          <i style="width: 24px; height: 24px;" class="fa-solid fa-circle-exclamation"></i>
        </span>
      <% end %>
      <h3>VL: <span class="fw-bold"><%= @remaining_vl < 0 ? 0 : @remaining_vl %>/15</span> remaining</h3>
      <div>
        <span class="fw-bold"><%= @approved_vl %></span> approved,
        <span class="fw-bold"><%= @pending_vl %></span> pending
      </div>
    </div>
  </div>
</div>

<div class="container col-lg-6 py-2 z-1">
  <div class="row">
    <div class="col-6" data-controller="modal">
      <%= form_with(url: cancel_leaves_path, method: :post) do |f| %>
        <%= f.hidden_field :id, class: "form-control" %>
        <%= render "modal",
              title: "Cancel",
              content: "Are you sure you want to cancel this leave request?",
              form: f
        %>
        
        <h4 class="fw-bold pb-2">Upcoming Leaves</h4>
        <% if @upcoming_leaves.size == 0 %>
          None
        <% else %>
          <% @upcoming_leaves.each do |leave| %>
            <div class="my-1 card">
              <div class="card-body border-start rounded border-4 <%= get_type_border(leave.leave_type) %>">
                <div class="card-title row">
                  <div class="col-9 d-flex flex-column justify-content-center">
                    <h5><span class="fw-bold"><%= leave.leave_type.capitalize %></span> (<%= leave.day_count %> day<%= "s" if leave.day_count > 1 %>)</h5>
                    <h6>
                      <%= leave.start_date.strftime("%b %-d") %><%= ", " + leave.start_date.year.to_s if leave.start_date.year != leave.end_date.year %>
                      - <%= leave.end_date.strftime("%b %-d, %Y") %>
                    </h6>
                  </div>
                  <div class="col-3 d-flex flex-column align-items-end justify-content-start">
                    <div class="badge <%= get_status_badge(leave.status)%> me-1">
                      <%= leave.status.upcase %>
                    </div>
                    <div class="d-flex align-items-center my-1">
                      <% if leave.status == "pending" %>
                        <div class="col-6">
                          <a class="btn btn-secondary mx-1"
                              href="<%= edit_leave_path(leave) %>"
                              data-bs-toggle="tooltip"
                              data-bs-title="Edit"
                          >
                            <i class="fa-solid fa-pen-to-square"></i>
                          </a>
                        </div>
                      <% end %>
                      <% if ((["pending", "approved"].include? leave.status) && (leave.start_date - Date.today >= 0)) %>
                        <div class="col-6">
                          <button class="btn btn-secondary mx-1"
                                  data-action="modal#open"
                                  onclick="event.preventDefault(); document.getElementById('id').value = <%= leave.id %>"
                                  data-bs-toggle="tooltip"
                                  data-bs-title="Cancel"
                          >
                            <i class="fa-solid fa-ban"></i>
                          </button>
                        </div>
                      <% end %>
                    </div>
                  </div>
                </div>
                <div class="card-text row">
                  <div class="col-9">
                    <div class="row">
                      <div class="col-4">
                        <div>Approver: </div>
                        <div>Reason: </div>
                      </div>
                      <div class="col-8">
                        <div><%= leave.approver.email %></div>
                        <div class="<%= "text-muted" if !leave.reason? %>"><%= leave.reason? ? leave.reason : "none" %></div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>

    <div class="col-6">    
      <h4 class="fw-bold pb-2">Past leaves</h4>
      <% if @past_leaves.size == 0 %>
        None
      <% else %>
          <% @past_leaves.each do |leave| %>
            <div class="my-1 card">
              <div class="card-body border-start rounded border-4 bg-body-secondary <%= get_type_border(leave.leave_type) %>">
                <div class="card-title row">
                  <div class="col-9 d-flex flex-column justify-content-center">
                    <h5><span class="fw-bold"><%= leave.leave_type.capitalize %></span> (<%= leave.day_count %> day<%= "s" if leave.day_count > 1 %>)</h5>
                    <h6>
                      <%= leave.start_date.strftime("%b %-d") %><%= ", " + leave.start_date.year.to_s if leave.start_date.year != leave.end_date.year %>
                      - <%= leave.end_date.strftime("%b %-d, %Y") %>
                    </h6>
                  </div>
                  <div class="col-3 d-flex flex-column align-items-end justify-content-start">
                    <div class="badge <%= get_status_badge(leave.status)%> me-1">
                      <%= leave.status.upcase %>
                    </div>
                    <div class="d-flex align-items-center my-1">
                      <% if leave.status == "pending" %>
                        <div class="col-6">
                          <a class="btn btn-secondary mx-1"
                              href="<%= edit_leave_path(leave) %>"
                              data-bs-toggle="tooltip"
                              data-bs-title="Edit"
                          >
                            <i class="fa-solid fa-pen-to-square"></i>
                          </a>
                        </div>
                      <% end %>
                      <% if ((["pending", "approved"].include? leave.status) && (leave.start_date - Date.today >= 0)) %>
                        <div class="col-6">
                          <button class="btn btn-secondary mx-1"
                                  data-action="modal#open"
                                  onclick="event.preventDefault(); document.getElementById('id').value = <%= leave.id %>"
                                  data-bs-toggle="tooltip"
                                  data-bs-title="Cancel"
                          >
                            <i class="fa-solid fa-ban"></i>
                          </button>
                        </div>
                      <% end %>
                    </div>
                  </div>
                </div>
                <div class="card-text row">
                  <div class="col-9">
                    <div class="row">
                      <div class="col-4">
                        <div>Approver: </div>
                        <div>Reason: </div>
                      </div>
                      <div class="col-8">
                        <div><%= leave.approver.email %></div>
                        <div class="<%= "text-muted" if !leave.reason? %>"><%= leave.reason? ? leave.reason : "none" %></div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
    </div>
  </div>
</div>

app/views/leaves/new.html.erb
<div class="container col-12 col-md-6 py-4">
  <h2>New Leave Request</h2>
  <%= render "form", leave: @leave %>
</div>