config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :employees

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "reimbursements#index"
  resources :reimbursements, only: [ :index, :new, :create ]
  resources :leaves, only: [ :index, :new, :create, :edit, :update ] do
    member do
      put :approve
      put :reject
    end
    collection do
      post :cancel
    end
  end

  get "*path" => redirect("/"), constraints: lambda { |req| !req.path.starts_with?("/rails/active_storage") }
end

app/models/reimbursement.rb
class Reimbursement < ApplicationRecord
  include ActionView::Helpers::NumberHelper

  belongs_to :employee
  belongs_to :category
  has_many :reimbursement_items
  has_one_attached :image

  validates :employee_id, presence: true
  validates :category_id, presence: true
  validates :participated_employee_ids, presence: true
  validates :activity_date, presence: true
  validates :invoice_reference_number, presence: true, length: { maximum: 255 }
  validates :invoice_amount, presence: true, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 10**6 } # 1,000,000
  validates :supplier, presence: true, length: { maximum: 255 }
  validate :unique_invoice_reference_number
  validates :image, attached: true,
                    content_type: [ "image/png", "image/jpeg" ],
                    size: { less_than: 10.megabytes, message: "is too large. Maximum size is 10 MB." }

  def participated_employees
    order_by_clause = participated_employee_ids.each_with_index.map { |id, index| "WHEN #{id} THEN #{index}" }.join(" ")
    Employee.where(id: participated_employee_ids, status: "active")
            .order(Arel.sql(ActiveRecord::Base.sanitize_sql_array("CASE id #{order_by_clause} END")))
  end

  def participated_employees_shares
    order_by_clause = participated_employee_ids.each_with_index.map { |id, index| "WHEN #{id} THEN #{index}" }.join(" ")
    ReimbursementItem.joins(:employee)
                     .where(reimbursement_id: id, employee_id: participated_employee_ids)
                     .order(Arel.sql(ActiveRecord::Base.sanitize_sql_array("CASE employees.id #{order_by_clause} END")))
  end

  def self.filed_reimbursements(employee_id)
    self.select("reimbursements.*, categories.name")
        .joins(:category)
        .where(employee_id: employee_id)
        .where.not(status: "cancelled")
        .order("reimbursements.activity_date DESC")
  end

  def self.item_breakdown(employee_id:, start_date:, end_date:)
    self.select("categories.name, reimbursements.activity_date, reimbursements.participated_employee_ids, reimbursement_items.shared_amount")
        .joins(:reimbursement_items)
        .joins(:category)
        .where(reimbursement_items: { employee_id: employee_id })
        .where("reimbursements.activity_date >= ?", start_date)
        .where("reimbursements.activity_date <= ?", end_date)
        .where.not(status: "cancelled")
        .order("reimbursements.activity_date DESC")
  end

  def formatted_activity_date
    activity_date.strftime("%B %d, %Y") if activity_date.present?
  end

  def formatted_invoice_amount
    format_amount(invoice_amount) if invoice_amount.present?
  end

  def formatted_reimbursable_amount
    format_amount(reimbursable_amount) if reimbursable_amount.present?
  end

  def formatted_reimbursed_amount
    format_amount(reimbursed_amount) if reimbursed_amount.present?
  end

  def formatted_shared_amount
    format_amount(shared_amount) if shared_amount.present?
  end

  private

  def unique_invoice_reference_number
    unique_reimbursement = Reimbursement.where(invoice_reference_number: invoice_reference_number)
                                        .where.not(id: id)
                                        .where.not(status: "cancelled")
                                        .exists?

    errors.add(:invoice_reference_number, "has already been taken") if unique_reimbursement
  end

  def format_amount(amount)
    number_to_currency(amount, unit: "₱")
  end
end

app/controllers/reimbursements_controller.rb
class ReimbursementsController < InheritedResources::Base
  http_basic_authenticate_with name: ENV["HTTP_AUTH_USERNAME"], password: ENV["HTTP_AUTH_PASSWORD"]

  before_action :categories, only: [ :index, :new, :create ]
  before_action :employees, only: [ :index, :new, :create ]
  before_action :active_employees, only: [ :index, :new, :create ]
  before_action :participated_employees, only: [ :create, :update ]

  def index
    reimbursement_service = ReimbursementServices::GetReimbursements.call(params)

    @filed_reimbursements = reimbursement_service[:filed_reimbursements]
    @reimbursement_items = reimbursement_service[:reimbursement_items]
    @item_breakdown = reimbursement_service[:item_breakdown]

    @employee = Employee.find(params[:employee_id]) if params[:employee_id].present?
  end

  def new
    @reimbursement = Reimbursement.new
  end

  def create
    service = ReimbursementServices::CreateReimbursement.call(reimbursement_params)

    if service[:success]
      flash[:success] = "Reimbursement created successfully."
    else
      flash[:error] = service[:errors].join(", ")
    end

    redirect_to new_reimbursement_path
  end

  private

  def reimbursement_params
    params.require(:reimbursement).permit(:employee_id, :category_id, :activity_date, :invoice_reference_number, :invoice_amount, :image, :reimbursable_amount, :reimbursed_amount, :supplier, :status, participated_employee_ids: [])
  end

  def participated_employees
    params[:reimbursement][:participated_employee_ids].reject!(&:blank?) if params[:reimbursement][:participated_employee_ids]
  end

  def categories
    @categories = Category.where(status: "active").order(:name)
  end

  def employees
    @employees = Employee.where(status: "active").order(:nickname)
  end

  def active_employees
    @active_employees = Employee.where(status: "active", active: true).order(:nickname).pluck(:nickname, :id)
  end
end

app/helpers/reimbursements_helper.rb
module ReimbursementsHelper
  def set_status_badge(status)
    case status
    when "pending"
      "secondary"
    when "reimbursed"
      "success"
    else
      "danger"
    end
  end

  def start_date(date)
    if date.day < 6
      (date.beginning_of_month - 1.month).change(day: 6)
    else
      date.beginning_of_month.change(day: 6)
    end
  end

  def format_amount(amount)
    number_to_currency(amount, unit: "₱")
  end

  def dynamic_greeting
    current_hour = Time.now.hour
    greeting = if current_hour < 12
                "Good Morning"
    elsif current_hour < 18
                "Good Afternoon"
    else
                "Good Evening"
    end
  end

  # Returns black or white depending on which contrasts better with the background
  def text_color_for(hex_color)
    hex = hex_color.delete('#')
    r, g, b = hex[0..1].hex, hex[2..3].hex, hex[4..5].hex

    brightness = (r * 299 + g * 587 + b * 114) / 1000
    brightness > 150 ? '#000000' : '#ffffff'
  end

  def rgba_color(hex, alpha = 1.0)
    hex = hex.delete('#')
    r = hex[0..1].hex
    g = hex[2..3].hex
    b = hex[4..5].hex

    "rgba(#{r}, #{g}, #{b}, #{alpha})"
  end
end

app/views/reimbursements/_availed_activities.html.erb
<div class="col-12 col-md-6 mt-3 mt-md-0 card card-body card-box-shadow availed-activities-container equal-height">
  <% if @item_breakdown.present? %>
    <div class="equal-height">
      <div class="table-responsive">
          <table class="table caption-top">
            <caption class="pt-0">Availed Activities</caption>
            <thead class="table-light">
              <tr>
                <th scope="col">Activity</th>
                <th scope="col">Engaged Employees</th>
                <th class="text-end" scope="col">Consumption</th>
              </tr>
            </thead>
            <tbody>
              <% @item_breakdown.each do |item| %>
                <%
                  participated_employees = item.participated_employees.map do |employee|
                    employee.active ? employee.nickname : "#{employee.nickname} (Inactive)"
                  end.join(", ")
                %>
                <tr>
                  <td class="text-truncate table-width-150">
                    <div class="d-flex">
                      <div>
                        <%= item.name %>
                        <div class="text-muted fs-7">
                          <%= item.formatted_activity_date %>
                        </div>
                      </div>
                    </div>
                  </td>
                  <td class="participated-employee-cell" title="<%= participated_employees %>"><%= participated_employees %></td>
                  <td class="text-end"><%= item.formatted_shared_amount %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
      </div>
    </div>
  <% else %>
    <div class="d-flex justify-content-center">
      <%= image_tag("Robot_Working.gif", height: 200, width: 240 )%>
    </div>
    
    <div class="d-flex flex-column mx-auto my-2">
      <p class="text-center fw-bold me-2 mb-0">Nothing to display yet.</p>
      <%= link_to new_reimbursement_path(employee_id: params[:employee_id]), class: "btn btn-sm btn-primary rounded-pill" do %>
        File Reimbursement <i class="bi bi-arrow-right-circle"></i>
      <% end %>
    </div>
  <% end %>
</div>

app/views/reimbursements/_employee_search_form.html.erb
<div class="py-5 px-3 px-md-0 rounded-bottom hero-section">
  <div class="text-center">
    <%= image_tag("loudcloud_logo.png", width: 230, height: 95) %>
    <h1 class="display-6 fw-bold">EE Program - Budget Tracker</h1>
  </div>
  <%= form_with(url: reimbursements_path, method: :get) do |form| %>
    <div class="col-12 col-md-7 mx-auto">
      <div class="row d-flex justify-content-center">
        <div class="col-12 col-md-5 px-md-0 mb-2 mb-md-0">
          <%= form.select :employee_id, @active_employees, { prompt: "Select an employee", selected: params[:employee_id] }, { id: 'employee_select', data: { controller: 'employee_select' }, required: true } %>
        </div>
        <div class="col-7 col-md-3 pe-0 mb-2 mb-md-0">
          <%
            month = params.dig(:date, :month)&.to_i
            selected_month = (1..12).include?(month) ? month : Date.today.month
          %>
          <%= select_month(selected_month, { prompt: 'Choose month', field_name: 'month' }, { id: 'month_select', data: { controller: 'employee_select' }, required: true }) %>
        </div>
        <div class="col-5 col-md-2 mb-2 mb-md-0">
          <% selected_year = params.dig(:date, :year)&.to_i || Date.today.year %>
          <%= select_year(selected_year, { start_year: 2024, end_year: Date.today.year, prompt: 'Choose year', field_name: 'year' }, { id: 'year_select', data: { controller: 'employee_select' }, required: true }) %>
        </div>
        <div class="d-none d-md-block col-auto">
          <%= form.button class: "btn btn-success rounded-circle" do %>
            <i class="fa-solid fa-magnifying-glass"></i>
          <% end %>
        </div>
        <div class="d-md-none col-12">
          <%= form.submit "Search", class: "btn btn-success col-12" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/reimbursements/_filed_reimbursements.html.erb
<% if @filed_reimbursements.present? %>
  <div class="card collapse" id="filed_reimbursements_collapse">
    <div class="card-body">
      <div class="table-responsive">
        <table class="table caption-top">
          <caption class="pt-0">Filed Reimbursements</caption>
          <thead class="table-light">
            <th scope="col">Activity</th>
            <th scope="col">Supplier</th>
            <th scope="col">Reimbursed To</th>
            <th scope="col">Engaged Employees</th>
            <th class="text-end" scope="col">Invoice Amount</th>
          </thead>
          <tbody>
            <% @filed_reimbursements.each do |reimbursement| %>
              <% participated_employees_shares = reimbursement.participated_employees_shares.map { |item| "#{item.employee.nickname}: #{format_amount(item.shared_amount)}" }.join("<br>").html_safe %>
              <%
                participated_employees = reimbursement.participated_employees.map do |employee|
                  employee.active ? employee.nickname : "#{employee.nickname} (Inactive)"
                end.join(", ")
              %>
              <tr>
                <td class="text-truncate table-width-150">
                  <div class="d-flex">
                    <div>
                      <%= reimbursement.name %>
                      <div class="text-muted fs-7">
                        <%= reimbursement.formatted_activity_date %>
                      </div>
                    </div>
                  </div>
                </td>
                <td class="text-truncate table-width-200">
                  <div class="d-flex">
                    <div title="<%= reimbursement.supplier %>">
                      <%= reimbursement.supplier %>
                      <div class="text-muted fs-7" title="<%= reimbursement.invoice_reference_number %>">
                        <% if reimbursement.image.attached? %>
                          <%= link_to "Reference Number: #{reimbursement.invoice_reference_number}", url_for(reimbursement.image), target: "_blank", rel: "noopener" %>
                        <% else %>
                          Reference Number: <%= reimbursement.invoice_reference_number %>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </td>
                <td>
                  <div class="d-flex">
                    <div>
                      <%= reimbursement.employee.nickname %>
                    </div>
                    <div class="ms-1" data-controller="popover">
                      <a tabindex="0" class="btn btn-sm p-0 border-0 fs-7" data-bs-custom-class="custom-popover" role="button" data-bs-toggle="popover" data-bs-html="true" data-bs-trigger="focus" data-bs-title="Benefit Per Employee" data-bs-content="<%= participated_employees_shares %>"><i class="fa-solid fa-circle-info text-black-50"></i></a>
                    </div>
                  </div>
                </td>
                <td class="participated-employee-cell" title="<%= participated_employees %>">
                  <%= participated_employees %>
                </td>
                <td class="text-end"><%= reimbursement.formatted_invoice_amount %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

  <div class="d-flex align-items-center" data-controller="toggle">
    <div class="flex-grow-1 border-bottom"></div>

    <p class="mx-3 my-2">
      <button class="btn btn-primary btn-sm border-0 rounded-pill px-3" type="button" data-bs-toggle="collapse" data-bs-target="#filed_reimbursements_collapse" aria-expanded="false" aria-controls="filed_reimbursements_collapse" data-action="click->toggle#toggle" data-toggle-target="button">
        <span data-toggle-target="text">View All Reimbursements</span>
        <i class="bi bi-arrow-down-short" data-toggle-target="icon"></i>
      </button>
    </p>

    <div class="flex-grow-1 border-bottom"></div>
  </div>
<% end %>

app/views/reimbursements/_form.html.erb
<%= form_with(model: reimbursement, data: { controller: "form-validation", action: "submit->form-validation#validateForm" }) do |form| %>
  <div class="container col-12 col-md-8 col-lg-6 pt-4">
    <%= render 'shared/flashes' %>
    <%= render 'shared/toast' %>
    
    <h3 class="fw-bold mb-0">EE Program Benefit Request Form</h3>

    <div class="d-flex align-items-center gap-2">
      <small class="mb-2 text-muted fst-italic">
        Please read the
        <a data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample" class="text-decoration-underline">
          filing instructions
        </a>
        before submitting your request.
      </small>
    </div>


    <div class="collapse" id="collapseExample">
      <div class="card card-body">
        <p>Please ensure all requirements are fulfilled before filing your benefit request:</p>

        <ol>
          <li>Have an invoice from the establishment ready. This invoice must be named to  <strong>LOUDCLOUD INC.</strong>, <strong>TIN# 008-052-609-000</strong>, with address at <strong>1 Champaca St., Roxas District, Quezon City 1103</strong>.</li>
          <li>Make sure to check the invoice date! An invoice related to the EE Program must be filed no later than the 5th day of the month following the Invoice Date.</li>
        </ol>

        <p>Note that Benefit Requests with insufficient or erroneous requirements may be denied. For questions and clarifications, contact any member of HR & Admin.</p>
      </div>
    </div>

    <div class="row">
      <div class="mb-2">
          <%= form.label :category_id, "Select an activity", class: "form-label" %>

          <div class="row g-md-3" style="max-height: 400px; overflow-y: auto;">
            <% @categories.each do |category| %>
              <div class="col-12 col-md-6">
                <label class="d-flex align-items-center justify-content-between rounded p-3 mb-2 mb-lg-0 fw-bold" style="cursor: pointer; background-color: <%= rgba_color(category.icon_color, 0.15) %>; color: <%= text_color_for(category.icon_color) %>;">

                  <div class="d-flex align-items-center gap-3">
                    <i class="<%= category.icon %> fs-1" style="color: <%= category.icon_color %>;"></i>
                    <p class="mb-0 fw-medium"><%= category.name %></p>
                  </div>

                  <%= form.radio_button :category_id, category.id, required: true, class: "form-check-input", style: "transform: scale(1.2); opacity: 0.7;" %>
                </label>

              </div>
            <% end %>
          </div>
        </div>


      <div class="col-6">
        <%= form.label :employee_id, class: "form-label" %>
        <%= form.select :employee_id, options_for_select(@active_employees, selected: params[:employee_id] || nil), { prompt: "Select an employee" }, id: 'employee_select', data: { controller: 'employee_select' }, required: true %>
      </div>

      <div class="col-6">
        <%= form.label :activity_date, class: "form-label" %>
        <%= form.date_field :activity_date, max: Date.today, class: "form-control", required: true %>
      </div>

      <div class="col-12 col-md-7">
        <%= form.label :invoice_reference_number, "Reference Number", class: "form-label" %>
        <%= form.text_field :invoice_reference_number, class: "form-control", placeholder: "e.g., INV-12345-#{Date.today.year}", required: true %>
      </div>

      <div class="col-12 col-md-5">
        <%= form.label :invoice_amount, class: "form-label" %>

        <div class="input-group">
          <span class="input-group-text">₱</span>
          <%= form.text_field :invoice_amount, class: "form-control", placeholder: "Enter invoice amount", required: true %>
        </div>
      </div>

      <div>
        <%= form.label :participated_employee_ids, "Participated Employees", class: "form-label" %>
        <%= form.select :participated_employee_ids, 
              options_for_select(@employees.map { |employee|
                nickname = employee.active ? employee.nickname : "#{employee.nickname} (Inactive)"
                [nickname, employee.id]
              },
              selected: params[:employee_id] || nil), 
              { prompt: "Select employees" }, 
              { 
                id: 'employee_select',
                multiple: true,
                required: true,
                data: { controller: 'select', select_target: "employee", action: "change->select#validate" }
              } 
        %>

        <div id="participated_employees_validation" class="invalid-feedback">
          Please select at least 2 employees.
        </div>
      </div>

      <div>
        <%= form.label :supplier, class: "form-label" %>
        <%= form.text_field :supplier, class: "form-control", placeholder: "Enter supplier", required: true %>
      </div>

      <div data-controller="image-validation">
        <%= form.label :image, "Invoice Image", class: "form-label" %>        
        <%= form.file_field :image, accept: "image/*", class: "form-control", required: true, data: { image_validation_target: "fileInput" } %>

        <div id="invoice_image_validation" class="invalid-feedback" data-image-validation-target="imageTypeErrorMessage">
          Please upload an image file (JPG, PNG, JPEG, etc.).
        </div>

        <div class="invalid-feedback" data-image-validation-target="fileSizeErrorMessage">
          File size should not exceed 10 MB.
        </div>

        <span class="form-text text-muted fst-italic">Maximum file size: 10mb</span>
      </div>

      <div class="d-flex justify-content-end my-3">
        <%= form.submit "Submit", id: "submit_btn", class: "btn btn-primary col-12 col-md-auto", data: { form_validation_target: "submit" } %>
      </div>
    </div>
  </div>
<% end %>

app/views/reimbursements/_item_breakdown.html.erb
<% if @item_breakdown.present? %>
  <div class="col-12 col-md-6 mt-3 mt-md-0">
    <div class="card card-body equal-height item-breakdown-card">
      <div class="table-responsive">
          <table class="table">
            <thead class="table-light">
              <tr>
                <th scope="col">Activity</th>
                <th scope="col">Employees</th>
                <th class="text-end" scope="col">Consumption</th>
              </tr>
            </thead>
            <tbody>
              <% @item_breakdown.each do |item| %>
                <% participated_employees = item.participated_employees.map(&:nickname).join(", ") %>
                <tr>
                  <td class="text-truncate table-width-150">
                    <div class="d-flex">
                      <div>
                        <%= item.name %>
                        <div class="text-muted fs-7">
                          <%= item.formatted_activity_date %>
                        </div>
                      </div>
                    </div>
                  </td>
                  <td class="text-truncate table-width-180" title="<%= participated_employees %>"><%= participated_employees %></td>
                  <td class="text-end"><%= item.formatted_shared_amount %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
      </div>
    </div>
  </div>
<% else %>
  <div class="col-12 col-md-6 mt-3 mt-md-0">
    <div class="card card-body equal-height item-breakdown-card">
      <div class="d-flex justify-content-center">
        <%= image_tag("Robot_Working.gif", height: 200, width: 240 )%>
      </div>
      
      <div class="d-flex flex-column mx-auto my-2">
        <p class="text-center fw-bold me-2 mb-0">Nothing to display yet.</p>
        <%= link_to new_reimbursement_path(employee_id: params[:employee_id]), class: "btn btn-sm btn-primary rounded-pill" do %>
          File Reimbursement <i class="bi bi-arrow-right-circle"></i>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/reimbursements/_program_balance.html.erb
<div class="col-12 col-md-6">
  <div class="row row-cols-1 g-4">
    <% total_spent = 0 %>
    <% @categories.each_with_index do |category, index| %>
      <% total_shared_amount = @reimbursement_items.find { |item| item.category_id == category.id }&.total_shared_amount || 0 %>
      <% total_spent += total_shared_amount %>
      <div class="col">
        <div class="card usage-card card-box-shadow">
          <div class="icon-background">
            <i class="<%= category.icon %>" style="color: <%= category.icon_color %>;"></i>
          </div>
          <div class="card-body text-end">
            <h5 class="card-title">
              <%= format_amount([ENV['MONTHLY_BUDGET'].to_i - total_shared_amount, 0].max) %>
              <span class="fs-6 fw-normal text-muted">left</span>
            </h5>

            <p class="card-text text-muted"><%= category.name %></p>
          </div>
        </div>
      </div>
    <% end %>

    <div class="col">
      <div class="card usage-card card-box-shadow">
        <div class="icon-background">
          <i class="fa-solid fa-money-bills fa-3x" style="color: #a3fc97;"></i>
        </div>
        <div class="card-body text-end">
          <h5 class="card-title"><%= format_amount(total_spent) %></h5>
          <p class="card-text text-muted">Total Spent</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reimbursements/_reimbursement.html.erb
<div id="<%= dom_id reimbursement %>">
  <p>
    <strong>Employee:</strong>
    <%= reimbursement.employee_id %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= reimbursement.category_id %>
  </p>

  <p>
    <strong>Activity date:</strong>
    <%= reimbursement.activity_date %>
  </p>

  <p>
    <strong>Invoice reference number:</strong>
    <%= reimbursement.invoice_reference_number %>
  </p>

  <p>
    <strong>Invoice amount:</strong>
    <%= reimbursement.invoice_amount %>
  </p>

  <p>
    <strong>Reimbursable amount:</strong>
    <%= reimbursement.reimbursable_amount %>
  </p>

  <p>
    <strong>Reimbursed amount:</strong>
    <%= reimbursement.reimbursed_amount %>
  </p>

  <p>
    <strong>Participated employee ids:</strong>
    <%= reimbursement.participated_employee_ids %>
  </p>

  <p>
    <strong>Supplier:</strong>
    <%= reimbursement.supplier %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= reimbursement.status %>
  </p>

</div>

app/views/reimbursements/_usage.html.erb
<div class="col-12 col-md-6">
  <div class="d-flex justify-content-between" data-controller="toggle">
    <!--<% if @item_breakdown.present? %>
      <p class="mb-2">
        <button class="btn btn-outline-secondary btn-sm border-0" type="button" data-bs-toggle="collapse" data-bs-target="#breakdown_collapse" aria-expanded="false" aria-controls="breakdown_collapse" data-action="click->toggle#toggle" data-toggle-target="button">
          <span data-toggle-target="text">Show more</span>
          <i class="bi bi-arrow-down-short" data-toggle-target="icon"></i>
        </button>
      </p>
    <% end %>-->
  </div>
  <div class="row row-cols-1 g-4">
    <% total_spent = 0 %>
    <% @categories.each_with_index do |category, index| %>
      <% total_shared_amount = @reimbursement_items.find { |item| item.category_id == category.id }&.total_shared_amount || 0 %>
      <% total_spent += total_shared_amount %>
      <div class="col">
        <div class="card usage-card equal-height">
          <div class="icon-background">
            <i class="<%= category.icon %>" style="color: <%= category.icon_color %>;"></i>
          </div>
          <div class="card-body text-end">
            <h5 class="card-title"><%= format_amount(ENV['MONTHLY_BUDGET'].to_i - total_shared_amount) %></h5>
            <p class="card-text text-muted"><%= category.name %></p>
          </div>
        </div>
      </div>
    <% end %>

    <div class="col">
      <div class="card usage-card equal-height">
        <div class="icon-background">
          <i class="fa-solid fa-money-bills fa-3x" style="color: #a3fc97;"></i>
        </div>
        <div class="card-body text-end">
          <h5 class="card-title"><%= format_amount(total_spent) %></h5>
          <p class="card-text text-muted">Total Spent</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reimbursements/edit.html.erb
<% content_for :title, "Editing reimbursement" %>

<h1>Editing reimbursement</h1>

<%= render "form", reimbursement: @reimbursement %>

<br>

<div>
  <%= link_to "Show this reimbursement", @reimbursement %> |
  <%= link_to "Back to reimbursements", reimbursements_path %>
</div>

app/views/reimbursements/index.html.erb
<div class="col-12">
  <%= render 'employee_search_form' %>
  <% if params[:employee_id].present? %>
    <div class="col-11 mx-auto">
      <div class="row my-3">
        <div>
          <h4 class="fw-bold mb-0"> <%= dynamic_greeting %>, <%= @employee.nickname %>! <%= image_tag("wave.gif", height: 25, width: 25 )%></h4>
          <p class="fs-6 text-muted">
            <%
              month = params[:date][:month].to_i
              selected_month = (1..12).include?(month) ? month : Date.today.month
            %>
            <%= "#{@employee.nickname}#{@employee.nickname.end_with?('s') ? '’' : '’s'} activity in #{Date::MONTHNAMES[selected_month]} #{params.dig(:date, :year)&.to_i}" %>
          </p>
        </div>
        <div class="row p-0 m-0 col-12">
          <%= render 'program_balance' %>
          <%= render 'availed_activities' %>
        </div>
      </div>
      <%= render 'filed_reimbursements' %>
    </div>
  <% end %>
</div>

app/views/reimbursements/new.html.erb
<% content_for :title, "EE Program Benefit Request Form" %>
<%= render "form", reimbursement: @reimbursement %>

app/views/reimbursements/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @reimbursement %>

<div>
  <%= link_to "Edit this reimbursement", edit_reimbursement_path(@reimbursement) %> |
  <%= link_to "Back to reimbursements", reimbursements_path %>

  <%= button_to "Destroy this reimbursement", @reimbursement, method: :delete %>
</div>