config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :employees

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "reimbursements#index"
  resources :reimbursements, only: [ :index, :new, :create ]
  resources :leaves, only: [ :index, :new, :create, :edit, :update ] do
    member do
      put :approve
      put :reject
    end
    collection do
      post :cancel
    end
  end

  get "*path" => redirect("/"), constraints: lambda { |req| !req.path.starts_with?("/rails/active_storage") }
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg shadow-sm bg-light fixed-top z-3">
  <div class="container-fluid">
    <div>
      <a class="navbar-brand" href="/">
        <%= image_tag("loudcloud_logo.png", width: 90, height: 35) %>
      </a>
  </div>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Budget Tracker
          </a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="/">Dashboard</a>
            <a class="dropdown-item" href="<%= new_reimbursement_path(employee_id: params[:employee_id]) %>">
              File Reimbursement
            </a>
          </div>
        </li>
        <!--<li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle <%= 'disabled' if !employee_signed_in? %>" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Leaves Tracker
          </a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="<%= leaves_path %>">My Leaves</a>
            <a class="dropdown-item" href="<%= new_leave_path() %>">
              File Leave Request
            </a>
          </div>
        </li>-->
      </ul>
    </div>
    <div class="d-flex align-items-center">
      <!--<% if employee_signed_in? %>
        <div class="dropdown mx-3">
          <a class="nav-link dropdown-toggle d-flex align-items-center" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <span style="width: 36px; height: 36px;" class="mx-2 border border-secondary border-2 rounded-circle d-flex align-items-center justify-content-center">
              <i class="fa-regular fa-user"></i>
            </span>
            <%= current_employee.nickname %> 
          </a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="<%= edit_employee_registration_path %>">Update password</a>
            <a class="dropdown-item" href="<%= destroy_employee_session_path  %>" data-turbo-method="delete">Sign out</a>
          </div>
        </div>
      <% else %>
        <a class="btn btn-primary mx-2" href="<%= new_employee_session_path %>">Sign in</a>
      <% end %>
      <% if admin_user_signed_in? %>
        <a class="btn btn-outline-primary" href="<%= admin_root_path %>">Go to admin module</a>
      <% else %>
        <a class="btn btn-outline-primary mx-2" href="<%= admin_user_session_path %>">Sign in as admin</a>
      <% end %>
    </div>-->
    <a class="btn btn-outline-primary" href="<%= admin_root_path %>">Sign in</a>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Budget Tracker" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/favicon.png" type="image/png">
    <link rel="apple-touch-icon" href="/icon.png">
    <link href="https://cdn.jsdelivr.net/npm/tom-select@2.3.1/dist/css/tom-select.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/tom-select@2.3.1/dist/js/tom-select.complete.min.js"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div style="margin-top: 56px;">
      <%= yield %>
    </div>
  </body>
</html>